name: 'Build and Test'

on:
  workflow_call:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build-and-test:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        go: [ '1.22' ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-tests-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install bazelisk
        run: |
          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.19.0/bazelisk-linux-amd64"
          mkdir -p "${GITHUB_WORKSPACE}/bin/"
          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
      - name: Build
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" build //...
      - name: Test
        run: |
          "${GITHUB_WORKSPACE}/bin/bazel" test //...
